default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sakurama_development

test:
  <<: *default
  database: sakurama_test

production:
  <<: *default
  database: sakurama_production
  username: sakurama
  password: <%= ENV['SAKURAMA_DATABASE_PASSWORD'] %>
